requirejs.config({
    paths:{
        "jquery":"./js/libs/jquery-3.3.1",
        "banner":"./js/libs/jquery.banner",
        "data":"./js/libs/data",
        "fujin":"./js/fujin",
        "index":"./js/index"
    }
})